### ISSUE TITLE
Repository returns error on insert with mysql2 dataprovider and autoincrement id entity

### ISSUE THREAD

**Issue by khairul169** [remult/remult#134]
**Describe the bug**
When trying to insert some data using mysql data provider and an entity with autoIncrement() data type, it will throw an error, but is successfully inserted into the database.
```
.returning() is not supported by mysql and will not have any effect.
Error: Undefined binding(s) detected when compiling WHERE. Undefined column(s): [id] query: where `id` = ?
    at QueryCompiler_MySQL.toSQL (D:\Projects\App\remult\remult-test\node_modules\knex\lib\query\querycompiler.js:110:13)
    at compileCallback (D:\Projects\App\remult\remult-test\node_modules\knex\lib\formatter\formatterUtils.js:13:19)
    at rawOrFn (D:\Projects\App\remult\remult-test\node_modules\knex\lib\formatter\wrappingFormatter.js:225:7)
    at QueryCompiler_MySQL.whereWrapped (D:\Projects\App\remult\remult-test\node_modules\knex\lib\query\querycompiler.js:1084:17)
    at QueryCompiler_MySQL.where (D:\Projects\App\remult\remult-test\node_modules\knex\lib\query\querycompiler.js:573:34)
    at D:\Projects\App\remult\remult-test\node_modules\knex\lib\query\querycompiler.js:133:40
    at Array.forEach (<anonymous>)
    at QueryCompiler_MySQL.select (D:\Projects\App\remult\remult-test\node_modules\knex\lib\query\querycompiler.js:132:16)
    at QueryCompiler_MySQL.toSQL (D:\Projects\App\remult\remult-test\node_modules\knex\lib\query\querycompiler.js:73:29)
    at Builder.toSQL (D:\Projects\App\remult\remult-test\node_modules\knex\lib\query\querybuilder.js:83:44)
```

**To Reproduce**
1. Grab remult instance using mysql2 provider and get the repo
2. Create entity with auto incremental id
```
import { Entity, Fields } from "remult";

@Entity("tasks")
export class Task {
  @Fields.autoIncrement()
  id!: number;

  @Fields.string()
  title = "";
}
```
4. Insert some data
```
let task = await remult.repo(Task).insert({ title: "Test Task" });
console.log("CREATE", task);
```
6. or clone and run this sample project: https://github.com/khairul169/remult-test-mysql

**Expected behavior**
Expected to return object of the task including its id

**Screenshots**
![image](https://user-images.githubusercontent.com/10296472/197321185-0b0ede0f-a4cd-47d6-a9a9-7f153528c7da.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 19043.1021
 - Browser: Chrome
 - Version: NodeJS v16.13.0

**Additional context**
Tested on postgres and jsonprovider, it works well.. only error with mysql2

**Comment by noam-honig** [comment]
Hi @khairul169, I've fixed the issue you reported. Can you get version 0.16.4 and see if it resolves your issue?

**Comment by khairul169** [comment]
> Hi @khairul169, I've fixed the issue you reported. Can you get version 0.16.4 and see if it resolves your issue?

It works perfectly! 
but it still prints a warning message about returning not supported by mysql though..

![image](https://user-images.githubusercontent.com/10296472/197324391-decce07f-a5cc-4143-9be6-36877431497f.png)

**Comment by noam-honig** [comment]
Hi @khairul169, sorry about that - I just fixed that.

I was focused on the green test result - and missed the console :)

see:
https://github.com/remult/remult/releases/tag/v0.16.5

**Comment by khairul169** [comment]
Hi @noam-honig, thank you so much for quick fixes! :) 👍
