### ISSUE TITLE
field.entityDefs.entityType vs field.target

### ISSUE THREAD

**Issue by jycouet** [remult/remult#239]
**Describe the bug**
From a field, I would like to get its `repo`

When I do:
```ts
const repo = remult.repo(field.entityDefs.entityType)
```
I'm able to  access the repo. But as `entityDefs` is not exposed in typescript, I have to add `// @ts-ignore`. _That not that nice._

A valid typescript would be to use `field.target` like this:
```ts
const repo = remult.repo(field.target)
```
But here, I get an error when I use it:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'constructor')
    at getEntitySettings (getEntityRef.js:21:42)
    at createOldEntity (RepositoryImplementation.js:537:16)
    at new RepositoryImplementation (RepositoryImplementation.js:84:22)
    at _Remult.repo (context.js:60:38)
    at get metadata [as metadata] (remult-proxy.js:140:45)
    at getRepoDisplayValue (helper.ts:24:14)
    at Array.getLinkDisplayValue (Grid.svelte:33:6)
    at get_if_ctx_1 (Grid.svelte:90:44)
    at select_block_ctx (Grid.svelte:89:49)
    at create_each_block_1 (Grid.svelte:89:49)
```

**Expected behavior**
A clear way to get the repo from a field.

**Comment by noam-honig** [comment]
(await col.entityRef.repository.count({
          [col.metadata.key]: col.value,
        })) == 0
