### ISSUE TITLE
getaddrinfo ENOTFOUND base

### ISSUE THREAD

**Issue by YeudaBy** [remult/remult#304]
**Describe the bug**
I faced a problem when connecting to pg db, as show in the logs below, i can not connect to the db properly.

**To Reproduce**
Using remult v: ^0.22.10
pg v: ^8.11.3
node v: 18.15.0

remult configuration:
```
export default remultNext({
    entities: [
        Procedure
    ],
    dataProvider:
        createPostgresDataProvider()
})

```

Entity code:
```
@Entity("procedure", {
    allowApiCrud: true,
})
export class Procedure extends IdEntity {
    @Fields.string()
    title!: string;

    @Fields.string()
    description!: string;

    @Fields.string()
    procedure!: string;

    @Fields.number()
    views: number = 0;

    @Fields.createdAt()
    createdAt!: Date;

    @Fields.updatedAt()
    updatedAt!: Date;

    @Field(() => Array<string>)
    keywords: string[] = [];
}
```

logs:
```
  error: Error: getaddrinfo ENOTFOUND base
      at /Users/yeudaborodyanski/Documents/yedidon-call-center-old/node_modules/pg-pool/index.js:45:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'base'
  },
  query: 'SELECT 1 FROM information_Schema.tables WHERE table_name=$1',
  arguments: { '$1': 'procedure' }
}
failed verify structure of procedure  Error: getaddrinfo ENOTFOUND base
    at /Users/yeudaborodyanski/Documents/yedidon-call-center-old/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'base'
}
Schema ensured: 20.406ms
{
  error: Error: getaddrinfo ENOTFOUND base
      at /Users/yeudaborodyanski/Documents/yedidon-call-center-old/node_modules/pg-pool/index.js:45:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'base'
  },
  query: 'select id, title, description, procedure, views, createdAt, updatedAt, keywords\n' +
    ' from procedure Order By createdAt, id  limit 5 offset 0',
  arguments: {}
}
{
  message: 'getaddrinfo ENOTFOUND base',
  stack: [
    'Error: getaddrinfo ENOTFOUND base',
    '    at /Users/yeudaborodyanski/Documents/yedidon-call-center-old/node_modules/pg-pool/index.js:45:11',
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
  ],
  url: '/api/procedure?_sort=createdAt&_limit=5',
  method: 'GET'
}
{
  error: Error: getaddrinfo ENOTFOUND base
      at /Users/yeudaborodyanski/Documents/yedidon-call-center-old/node_modules/pg-pool/index.js:45:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'base'
  },
  query: 'select id, title, description, procedure, views, createdAt, updatedAt, keywords\n' +
    ' from procedure Order By createdAt, id  limit 5 offset 0',
  arguments: {}
}
{
  message: 'getaddrinfo ENOTFOUND base',
  stack: [
    'Error: getaddrinfo ENOTFOUND base',
    '    at /Users/yeudaborodyanski/Documents/yedidon-call-center-old/node_modules/pg-pool/index.js:45:11',
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
  ],
  url: '/api/procedure?_sort=createdAt&_limit=5',
  method: 'GET'
}
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by noam-honig** [comment]
@YeudaBy this seems like a pg configuration that can't connect to the db.
Try sending a connection string with the connectionString property of the postgres - as detailed in this article:
https://remult.dev/docs/databases.html#postgres

If you struggle with it and want my help, reach out to me on discord and I can zoom or something and help.

https://discord.gg/GXHk7ZfuG5
