### ISSUE TITLE
Error: couldn't find id to delete

### ISSUE THREAD

**Issue by alexchern** [remult/remult#309]
Hi,

I haven't done too much investigation on this, but when trying to delete multiple items one after another, remult crashes with the following error:

```
Waiting for the debugger to disconnect...
/home/alexc/Work/recaster/node_modules/remult/src/data-providers/array-entity-data-provider.js:256
                        throw new Error("couldn't find id to delete: " + id);
                              ^

Error: couldn't find id to delete: 424
    at ArrayEntityDataProvider.<anonymous> (/home/alexc/Work/recaster/node_modules/remult/src/data-providers/array-entity-data-provider.js:256:31)
    at step (/home/alexc/Work/recaster/node_modules/tslib/tslib.js:195:27)
    at Object.next (/home/alexc/Work/recaster/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/home/alexc/Work/recaster/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.2
```

Currently, I put a 'sleep' between the actions. With the sleep, it works as expected. I tried to find a place to wrap it with try/catch but could not figure it out so far. Probably, should spend more time on this.

Thanks,

Alex

**Comment by noam-honig** [comment]
Hi @alexchern 
This exception happens in the json db when you are trying to delete a row that isn't there.

If you think that this is not the case, can you reproduce it in this sandbox please? I'll investigate it

https://githubbox.com/remult/react-vite-express-starter

**Comment by alexchern** [comment]
Thanks. I'll do more testing.
