### ISSUE TITLE
Doesn't work with Deno 2 it seems

### ISSUE THREAD

**Issue by jarlah** [remult/remult#552]
**Describe the bug**
Doesn't work in Deno 2.0 due to some problems with @noble/hashes/sha3. Doesn't help adding noble hashes sha3 in imports. Then I get another error.

**To Reproduce**
following this tutorial 
https://dev.to/yonirapoport/build-a-full-stack-crud-app-using-denos-fresh-and-postgres-4l39
when adding remult like this in imports
```json
    "remult": "https://cdn.skypack.dev/remult?dts",
    "remult/remult-fresh": "https://cdn.skypack.dev/remult/remult-fresh?dts",
    "https://deno.land/std/node/fs.ts": "https://deno.land/std@0.216.0/node/fs.ts",
```
and adding routes/_middleware.ts
```typescript
import { remultFresh } from "remult/remult-fresh";

export const remultServer = remultFresh({ }, Response);

export const handler = remultServer.handle;
```
it fails with
```
error: Uncaught (in promise) TypeError: Relative import path "@noble/hashes/sha3" not prefixed with / or ./ or ../ and not in import map from "https://cdn.skypack.dev/-/@paralleldrive/cuid2@v2.2.2-D2JiuGi6yXDxJSuPVwna/dist=es2019,mode=imports/optimized/@paralleldrive/cuid2.js"
    at https://cdn.skypack.dev/-/@paralleldrive/cuid2@v2.2.2-D2JiuGi6yXDxJSuPVwna/dist=es2019,mode=imports/optimized/@paralleldrive/cuid2.js:1:24
  const manifest = (await import(toFileUrl(join(dir, "fresh.gen.ts")).href))
```
doesnt help adding noble hashes in imports
```json
    "@noble/hashes/sha3": "npm:@noble/hashes/sha3"
```
then i get 
```
error: Uncaught (in promise) SyntaxError: The requested module '@noble/hashes/sha3' does not provide an export named 'default' at https://cdn.skypack.dev/-/@paralleldrive/cuid2@v2.2.2-D2JiuGi6yXDxJSuPVwna/dist=es2019,mode=imports/optimized/@paralleldrive/cuid2.js:1:8
  const manifest = (await import(toFileUrl(join(dir, "fresh.gen.ts")).href))
```

**Expected behavior**
should work in Deno 2

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser n/a
 - Version: latest

**Additional context**
I know the article was meant for Deno 1, but is there so much differences ?

**Comment by noam-honig** [comment]
Hi, it seems like we'll need to release a version that doesn't use cuid2 - to support deno - we're working on it, lets see
